// <auto-generated />
using System;
using DataAccessLayer.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20231201121523_mig-identity")]
    partial class migidentity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CoreLayer.Entities.Concrete.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("CoreLayer.Entities.Concrete.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("EntityLayer.Concrete.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"), 1L, 1);

                    b.Property<string>("CategoryInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("CategoryPrice")
                        .HasColumnType("float");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryInfo = "If your goal want to seem fit and more powerful, you can click \"more information\" button.",
                            CategoryName = "Fitness",
                            CategoryPrice = 1200.0
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryInfo = "There are group lessons and personal lessons for kick box.You can click the \"More Information\" button and see opportunities for you. ",
                            CategoryName = "Kickbox",
                            CategoryPrice = 1700.0
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryInfo = "If you want to have fun and do sports at the same time, zumba is the best choice for you.",
                            CategoryName = "Zumba",
                            CategoryPrice = 1500.0
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryInfo = "If you want to more flexible body, pilates is the best choice for you.",
                            CategoryName = "Pilates",
                            CategoryPrice = 700.0
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryInfo = "If you do not have much time, you can work with a personal trainer.",
                            CategoryName = "Coaching",
                            CategoryPrice = 15.699999999999999
                        });
                });

            modelBuilder.Entity("EntityLayer.Concrete.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactId"), 1L, 1);

                    b.Property<string>("ContactContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContactId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Description", b =>
                {
                    b.Property<int>("DescriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DescriptionId"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("DescriptionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DescriptionId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Descriptions");

                    b.HasData(
                        new
                        {
                            DescriptionId = 1,
                            CategoryId = 1,
                            DescriptionName = "There are many variations of passages of Lorem Ipsum available, \r\n                        but the majority have suffered alteration in some form, by injected humour, \r\n                        or randomised words which don't look even slightly believable. \r\n                        If you are going to use a passage of Lorem Ipsum, you need to be sure \r\n                        there isn't anything embarrassing hidden in the middle of text. \r\n                        All the Lorem Ipsum generators on the Internet tend to repeat \r\n                        predefined chunks as necessary, making this the first true generator \r\n                        on the Internet. It uses a dictionary of over 200 Latin words, combined \r\n                        with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. \r\n                        The generated Lorem Ipsum is therefore always free from repetition, \r\n                        injected humour, or non-characteristic words etc."
                        },
                        new
                        {
                            DescriptionId = 2,
                            CategoryId = 1,
                            DescriptionName = "There are many variations of passages of Lorem Ipsum available, \r\n                            but the majority have suffered alteration in some form, by injected humour, \r\n                            or randomised words which don't look even slightly believable. \r\n                            If you are going to use a passage of Lorem Ipsum, you need to be sure \r\n                            there isn't anything embarrassing hidden in the middle of text. \r\n                            All the Lorem Ipsum generators on the Internet tend to repeat \r\n                            predefined chunks as necessary, making this the first true generator \r\n                            on the Internet. It uses a dictionary of over 200 Latin words, combined \r\n                            with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. \r\n                            The generated Lorem Ipsum is therefore always free from repetition, \r\n                            injected humour, or non-characteristic words etc."
                        },
                        new
                        {
                            DescriptionId = 3,
                            CategoryId = 1,
                            DescriptionName = "There are many variations of passages of Lorem Ipsum available, \r\n                        but the majority have suffered alteration in some form, by injected humour, \r\n                        or randomised words which don't look even slightly believable. \r\n                        If you are going to use a passage of Lorem Ipsum, you need to be sure \r\n                        there isn't anything embarrassing hidden in the middle of text. \r\n                        All the Lorem Ipsum generators on the Internet tend to repeat \r\n                        predefined chunks as necessary, making this the first true generator \r\n                        on the Internet. It uses a dictionary of over 200 Latin words, combined \r\n                        with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. \r\n                        The generated Lorem Ipsum is therefore always free from repetition, \r\n                        injected humour, or non-characteristic words etc."
                        },
                        new
                        {
                            DescriptionId = 4,
                            CategoryId = 2,
                            DescriptionName = "There are many variations of passages of Lorem Ipsum available, \r\n                        but the majority have suffered alteration in some form, by injected humour, \r\n                        or randomised words which don't look even slightly believable. \r\n                        If you are going to use a passage of Lorem Ipsum, you need to be sure \r\n                        there isn't anything embarrassing hidden in the middle of text. \r\n                        All the Lorem Ipsum generators on the Internet tend to repeat \r\n                        predefined chunks as necessary, making this the first true generator \r\n                        on the Internet. It uses a dictionary of over 200 Latin words, combined \r\n                        with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. \r\n                        The generated Lorem Ipsum is therefore always free from repetition, \r\n                        injected humour, or non-characteristic words etc."
                        },
                        new
                        {
                            DescriptionId = 5,
                            CategoryId = 2,
                            DescriptionName = "There are many variations of passages of Lorem Ipsum available, \r\n                        but the majority have suffered alteration in some form, by injected humour, \r\n                        or randomised words which don't look even slightly believable. \r\n                        If you are going to use a passage of Lorem Ipsum, you need to be sure \r\n                        there isn't anything embarrassing hidden in the middle of text. \r\n                        All the Lorem Ipsum generators on the Internet tend to repeat \r\n                        predefined chunks as necessary, making this the first true generator \r\n                        on the Internet. It uses a dictionary of over 200 Latin words, combined \r\n                        with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. \r\n                        The generated Lorem Ipsum is therefore always free from repetition, \r\n                        injected humour, or non-characteristic words etc."
                        },
                        new
                        {
                            DescriptionId = 6,
                            CategoryId = 2,
                            DescriptionName = "There are many variations of passages of Lorem Ipsum available, \r\n                        but the majority have suffered alteration in some form, by injected humour, \r\n                        or randomised words which don't look even slightly believable. \r\n                        If you are going to use a passage of Lorem Ipsum, you need to be sure \r\n                        there isn't anything embarrassing hidden in the middle of text. \r\n                        All the Lorem Ipsum generators on the Internet tend to repeat \r\n                        predefined chunks as necessary, making this the first true generator \r\n                        on the Internet. It uses a dictionary of over 200 Latin words, combined \r\n                        with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. \r\n                        The generated Lorem Ipsum is therefore always free from repetition, \r\n                        injected humour, or non-characteristic words etc."
                        },
                        new
                        {
                            DescriptionId = 7,
                            CategoryId = 3,
                            DescriptionName = "There are many variations of passages of Lorem Ipsum available, \r\n                        but the majority have suffered alteration in some form, by injected humour, \r\n                        or randomised words which don't look even slightly believable. \r\n                        If you are going to use a passage of Lorem Ipsum, you need to be sure \r\n                        there isn't anything embarrassing hidden in the middle of text. \r\n                        All the Lorem Ipsum generators on the Internet tend to repeat \r\n                        predefined chunks as necessary, making this the first true generator \r\n                        on the Internet. It uses a dictionary of over 200 Latin words, combined \r\n                        with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. \r\n                        The generated Lorem Ipsum is therefore always free from repetition, \r\n                        injected humour, or non-characteristic words etc."
                        },
                        new
                        {
                            DescriptionId = 8,
                            CategoryId = 3,
                            DescriptionName = "There are many variations of passages of Lorem Ipsum available, \r\n                        but the majority have suffered alteration in some form, by injected humour, \r\n                        or randomised words which don't look even slightly believable. \r\n                        If you are going to use a passage of Lorem Ipsum, you need to be sure \r\n                        there isn't anything embarrassing hidden in the middle of text. \r\n                        All the Lorem Ipsum generators on the Internet tend to repeat \r\n                        predefined chunks as necessary, making this the first true generator \r\n                        on the Internet. It uses a dictionary of over 200 Latin words, combined \r\n                        with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. \r\n                        The generated Lorem Ipsum is therefore always free from repetition, \r\n                        injected humour, or non-characteristic words etc."
                        },
                        new
                        {
                            DescriptionId = 9,
                            CategoryId = 3,
                            DescriptionName = "There are many variations of passages of Lorem Ipsum available, \r\n                        but the majority have suffered alteration in some form, by injected humour, \r\n                        or randomised words which don't look even slightly believable. \r\n                        If you are going to use a passage of Lorem Ipsum, you need to be sure \r\n                        there isn't anything embarrassing hidden in the middle of text. \r\n                        All the Lorem Ipsum generators on the Internet tend to repeat \r\n                        predefined chunks as necessary, making this the first true generator \r\n                        on the Internet. It uses a dictionary of over 200 Latin words, combined \r\n                        with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. \r\n                        The generated Lorem Ipsum is therefore always free from repetition, \r\n                        injected humour, or non-characteristic words etc."
                        },
                        new
                        {
                            DescriptionId = 10,
                            CategoryId = 4,
                            DescriptionName = "There are many variations of passages of Lorem Ipsum available, \r\n                        but the majority have suffered alteration in some form, by injected humour, \r\n                        or randomised words which don't look even slightly believable. \r\n                        If you are going to use a passage of Lorem Ipsum, you need to be sure \r\n                        there isn't anything embarrassing hidden in the middle of text. \r\n                        All the Lorem Ipsum generators on the Internet tend to repeat \r\n                        predefined chunks as necessary, making this the first true generator \r\n                        on the Internet. It uses a dictionary of over 200 Latin words, combined \r\n                        with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. \r\n                        The generated Lorem Ipsum is therefore always free from repetition, \r\n                        injected humour, or non-characteristic words etc."
                        },
                        new
                        {
                            DescriptionId = 11,
                            CategoryId = 4,
                            DescriptionName = "There are many variations of passages of Lorem Ipsum available, \r\n                        but the majority have suffered alteration in some form, by injected humour, \r\n                        or randomised words which don't look even slightly believable. \r\n                        If you are going to use a passage of Lorem Ipsum, you need to be sure \r\n                        there isn't anything embarrassing hidden in the middle of text. \r\n                        All the Lorem Ipsum generators on the Internet tend to repeat \r\n                        predefined chunks as necessary, making this the first true generator \r\n                        on the Internet. It uses a dictionary of over 200 Latin words, combined \r\n                        with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. \r\n                        The generated Lorem Ipsum is therefore always free from repetition, \r\n                        injected humour, or non-characteristic words etc."
                        },
                        new
                        {
                            DescriptionId = 12,
                            CategoryId = 4,
                            DescriptionName = "There are many variations of passages of Lorem Ipsum available, \r\n                        but the majority have suffered alteration in some form, by injected humour, \r\n                        or randomised words which don't look even slightly believable. \r\n                        If you are going to use a passage of Lorem Ipsum, you need to be sure \r\n                        there isn't anything embarrassing hidden in the middle of text. \r\n                        All the Lorem Ipsum generators on the Internet tend to repeat \r\n                        predefined chunks as necessary, making this the first true generator \r\n                        on the Internet. It uses a dictionary of over 200 Latin words, combined \r\n                        with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. \r\n                        The generated Lorem Ipsum is therefore always free from repetition, \r\n                        injected humour, or non-characteristic words etc."
                        },
                        new
                        {
                            DescriptionId = 13,
                            CategoryId = 5,
                            DescriptionName = "There are many variations of passages of Lorem Ipsum available, \r\n                        but the majority have suffered alteration in some form, by injected humour, \r\n                        or randomised words which don't look even slightly believable. \r\n                        If you are going to use a passage of Lorem Ipsum, you need to be sure \r\n                        there isn't anything embarrassing hidden in the middle of text. \r\n                        All the Lorem Ipsum generators on the Internet tend to repeat \r\n                        predefined chunks as necessary, making this the first true generator \r\n                        on the Internet. It uses a dictionary of over 200 Latin words, combined \r\n                        with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. \r\n                        The generated Lorem Ipsum is therefore always free from repetition, \r\n                        injected humour, or non-characteristic words etc."
                        },
                        new
                        {
                            DescriptionId = 14,
                            CategoryId = 5,
                            DescriptionName = "There are many variations of passages of Lorem Ipsum available, \r\n                        but the majority have suffered alteration in some form, by injected humour, \r\n                        or randomised words which don't look even slightly believable. \r\n                        If you are going to use a passage of Lorem Ipsum, you need to be sure \r\n                        there isn't anything embarrassing hidden in the middle of text. \r\n                        All the Lorem Ipsum generators on the Internet tend to repeat \r\n                        predefined chunks as necessary, making this the first true generator \r\n                        on the Internet. It uses a dictionary of over 200 Latin words, combined \r\n                        with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. \r\n                        The generated Lorem Ipsum is therefore always free from repetition, \r\n                        injected humour, or non-characteristic words etc."
                        },
                        new
                        {
                            DescriptionId = 15,
                            CategoryId = 5,
                            DescriptionName = "There are many variations of passages of Lorem Ipsum available, \r\n                        but the majority have suffered alteration in some form, by injected humour, \r\n                        or randomised words which don't look even slightly believable. \r\n                        If you are going to use a passage of Lorem Ipsum, you need to be sure \r\n                        there isn't anything embarrassing hidden in the middle of text. \r\n                        All the Lorem Ipsum generators on the Internet tend to repeat \r\n                        predefined chunks as necessary, making this the first true generator \r\n                        on the Internet. It uses a dictionary of over 200 Latin words, combined \r\n                        with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. \r\n                        The generated Lorem Ipsum is therefore always free from repetition, \r\n                        injected humour, or non-characteristic words etc."
                        });
                });

            modelBuilder.Entity("EntityLayer.Concrete.Image", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ImageId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            ImageId = 1,
                            CategoryId = 1,
                            ImageName = "fitness1.jpg"
                        },
                        new
                        {
                            ImageId = 2,
                            CategoryId = 1,
                            ImageName = "fitness2.jpg"
                        },
                        new
                        {
                            ImageId = 3,
                            CategoryId = 1,
                            ImageName = "fitness3.jpg"
                        },
                        new
                        {
                            ImageId = 4,
                            CategoryId = 2,
                            ImageName = "kickbox1.jpg"
                        },
                        new
                        {
                            ImageId = 5,
                            CategoryId = 2,
                            ImageName = "kickbox2.jpg"
                        },
                        new
                        {
                            ImageId = 6,
                            CategoryId = 2,
                            ImageName = "kickbox3.jpg"
                        },
                        new
                        {
                            ImageId = 7,
                            CategoryId = 3,
                            ImageName = "zumba1.jpg"
                        },
                        new
                        {
                            ImageId = 8,
                            CategoryId = 3,
                            ImageName = "zumba2.jpg"
                        },
                        new
                        {
                            ImageId = 9,
                            CategoryId = 3,
                            ImageName = "zumba3.jpg"
                        },
                        new
                        {
                            ImageId = 10,
                            CategoryId = 4,
                            ImageName = "pilates1.jpg"
                        },
                        new
                        {
                            ImageId = 11,
                            CategoryId = 4,
                            ImageName = "pilates2.jpg"
                        },
                        new
                        {
                            ImageId = 12,
                            CategoryId = 4,
                            ImageName = "pilates3.jpg"
                        },
                        new
                        {
                            ImageId = 13,
                            CategoryId = 5,
                            ImageName = "coaching1.jpg"
                        },
                        new
                        {
                            ImageId = 14,
                            CategoryId = 5,
                            ImageName = "coaching2.jpg"
                        },
                        new
                        {
                            ImageId = 15,
                            CategoryId = 5,
                            ImageName = "coaching3.jpg"
                        });
                });

            modelBuilder.Entity("EntityLayer.Concrete.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberId"), 1L, 1);

                    b.Property<string>("MemberEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberNameSurname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MemberStatus")
                        .HasColumnType("bit");

                    b.Property<string>("MemberUserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MemberId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("EntityLayer.Concrete.MemberCategory", b =>
                {
                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("MemberId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("MemberCategories");
                });

            modelBuilder.Entity("EntityLayer.Concrete.MemberTrainer", b =>
                {
                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.HasKey("MemberId", "TrainerId");

                    b.HasIndex("TrainerId");

                    b.ToTable("MemberTrainers");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Trainer", b =>
                {
                    b.Property<int>("TrainerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrainerId"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("NameSurname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrainerDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrainerImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TrainerId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Trainers");

                    b.HasData(
                        new
                        {
                            TrainerId = 1,
                            CategoryId = 1,
                            NameSurname = "Yusuf Dilekci",
                            TrainerDescription = "Some quick example text to build on the card title and make up the bulk of the card's content.",
                            TrainerImage = "trainer1.jpg"
                        },
                        new
                        {
                            TrainerId = 2,
                            CategoryId = 1,
                            NameSurname = "Savas Cebeci",
                            TrainerDescription = "Some quick example text to build on the card title and make up the bulk of the card's content.",
                            TrainerImage = "trainer2.jpg"
                        },
                        new
                        {
                            TrainerId = 3,
                            CategoryId = 2,
                            NameSurname = "Birol E.",
                            TrainerDescription = "Some quick example text to build on the card title and make up the bulk of the card's content.",
                            TrainerImage = "trainer3.jpg"
                        },
                        new
                        {
                            TrainerId = 4,
                            CategoryId = 3,
                            NameSurname = "Mert A.",
                            TrainerDescription = "Some quick example text to build on the card title and make up the bulk of the card's content.",
                            TrainerImage = "trainer4.jpg"
                        },
                        new
                        {
                            TrainerId = 5,
                            CategoryId = 3,
                            NameSurname = "Azat T.",
                            TrainerDescription = "Some quick example text to build on the card title and make up the bulk of the card's content.",
                            TrainerImage = "trainer5.jpg"
                        },
                        new
                        {
                            TrainerId = 6,
                            CategoryId = 4,
                            NameSurname = "Oguz R.",
                            TrainerDescription = "Some quick example text to build on the card title and make up the bulk of the card's content.",
                            TrainerImage = "trainer6.jpg"
                        },
                        new
                        {
                            TrainerId = 7,
                            CategoryId = 5,
                            NameSurname = "Sadik S.",
                            TrainerDescription = "Some quick example text to build on the card title and make up the bulk of the card's content.",
                            TrainerImage = "trainer7.jpg"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EntityLayer.Concrete.Description", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Category", "Category")
                        .WithMany("Descriptions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Image", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Category", "Category")
                        .WithMany("Images")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("EntityLayer.Concrete.MemberCategory", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Category", "Category")
                        .WithMany("Members")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.Member", "Member")
                        .WithMany("Categories")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("EntityLayer.Concrete.MemberTrainer", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Member", "Member")
                        .WithMany("Trainers")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.Trainer", "Trainer")
                        .WithMany("Members")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Trainer", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Category", "Category")
                        .WithMany("Trainers")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("CoreLayer.Entities.Concrete.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("CoreLayer.Entities.Concrete.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("CoreLayer.Entities.Concrete.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("CoreLayer.Entities.Concrete.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreLayer.Entities.Concrete.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("CoreLayer.Entities.Concrete.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EntityLayer.Concrete.Category", b =>
                {
                    b.Navigation("Descriptions");

                    b.Navigation("Images");

                    b.Navigation("Members");

                    b.Navigation("Trainers");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Member", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Trainers");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Trainer", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
