using EntityLayer.Concrete;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection.Metadata;
using System.Text;
using System.Threading.Tasks;

namespace DataAccessLayer.Concrete
{
    public class Context : DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=SportCenter;Trusted_Connection=True");
            
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            
            modelBuilder.Entity<MemberCategory>()
                .HasKey(x => new {x.MemberId, x.CategoryId});

            modelBuilder.Entity<MemberTrainer>()
                .HasKey(x => new { x.MemberId, x.TrainerId });

            modelBuilder.Entity<Category>()
                .HasData(
                    new Category() { CategoryId = 1, CategoryName = "Fitness", CategoryInfo = "If your goal want to seem fit and more powerful, you can click \"more information\" button.", CategoryPrice=1200},
                    new Category() { CategoryId = 2, CategoryName = "Kickbox", CategoryInfo = "There are group lessons and personal lessons for kick box.You can click the \"More Information\" button and see opportunities for you. ", CategoryPrice = 1700 },
                    new Category() { CategoryId = 3, CategoryName = "Zumba", CategoryInfo = "If you want to have fun and do sports at the same time, zumba is the best choice for you.", CategoryPrice = 1500 },
                    new Category() { CategoryId = 4, CategoryName = "Pilates", CategoryInfo = "If you want to more flexible body, pilates is the best choice for you.", CategoryPrice = 700 },
                    new Category() { CategoryId = 5, CategoryName = "Coaching", CategoryInfo = "If you do not have much time, you can work with a personal trainer.", CategoryPrice = 15.700 }
                );

            modelBuilder.Entity<Description>()
                .HasData(
                    new Description() { DescriptionId=1, CategoryId= 1, DescriptionName= "There are many variations of passages of Lorem Ipsum available, \r\n                        but the majority have suffered alteration in some form, by injected humour, \r\n                        or randomised words which don't look even slightly believable. \r\n                        If you are going to use a passage of Lorem Ipsum, you need to be sure \r\n                        there isn't anything embarrassing hidden in the middle of text. \r\n                        All the Lorem Ipsum generators on the Internet tend to repeat \r\n                        predefined chunks as necessary, making this the first true generator \r\n                        on the Internet. It uses a dictionary of over 200 Latin words, combined \r\n                        with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. \r\n                        The generated Lorem Ipsum is therefore always free from repetition, \r\n                        injected humour, or non-characteristic words etc." },
                    new Description() { DescriptionId =2, CategoryId = 1, DescriptionName = "There are many variations of passages of Lorem Ipsum available, \r\n                            but the majority have suffered alteration in some form, by injected humour, \r\n                            or randomised words which don't look even slightly believable. \r\n                            If you are going to use a passage of Lorem Ipsum, you need to be sure \r\n                            there isn't anything embarrassing hidden in the middle of text. \r\n                            All the Lorem Ipsum generators on the Internet tend to repeat \r\n                            predefined chunks as necessary, making this the first true generator \r\n                            on the Internet. It uses a dictionary of over 200 Latin words, combined \r\n                            with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. \r\n                            The generated Lorem Ipsum is therefore always free from repetition, \r\n                            injected humour, or non-characteristic words etc." },
                    new Description() { DescriptionId =3, CategoryId = 1, DescriptionName = "There are many variations of passages of Lorem Ipsum available, \r\n                        but the majority have suffered alteration in some form, by injected humour, \r\n                        or randomised words which don't look even slightly believable. \r\n                        If you are going to use a passage of Lorem Ipsum, you need to be sure \r\n                        there isn't anything embarrassing hidden in the middle of text. \r\n                        All the Lorem Ipsum generators on the Internet tend to repeat \r\n                        predefined chunks as necessary, making this the first true generator \r\n                        on the Internet. It uses a dictionary of over 200 Latin words, combined \r\n                        with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. \r\n                        The generated Lorem Ipsum is therefore always free from repetition, \r\n                        injected humour, or non-characteristic words etc." },
                    new Description() { DescriptionId = 4, CategoryId = 2, DescriptionName = "There are many variations of passages of Lorem Ipsum available, \r\n                        but the majority have suffered alteration in some form, by injected humour, \r\n                        or randomised words which don't look even slightly believable. \r\n                        If you are going to use a passage of Lorem Ipsum, you need to be sure \r\n                        there isn't anything embarrassing hidden in the middle of text. \r\n                        All the Lorem Ipsum generators on the Internet tend to repeat \r\n                        predefined chunks as necessary, making this the first true generator \r\n                        on the Internet. It uses a dictionary of over 200 Latin words, combined \r\n                        with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. \r\n                        The generated Lorem Ipsum is therefore always free from repetition, \r\n                        injected humour, or non-characteristic words etc." },
                    new Description() { DescriptionId = 5, CategoryId = 2, DescriptionName = "There are many variations of passages of Lorem Ipsum available, \r\n                        but the majority have suffered alteration in some form, by injected humour, \r\n                        or randomised words which don't look even slightly believable. \r\n                        If you are going to use a passage of Lorem Ipsum, you need to be sure \r\n                        there isn't anything embarrassing hidden in the middle of text. \r\n                        All the Lorem Ipsum generators on the Internet tend to repeat \r\n                        predefined chunks as necessary, making this the first true generator \r\n                        on the Internet. It uses a dictionary of over 200 Latin words, combined \r\n                        with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. \r\n                        The generated Lorem Ipsum is therefore always free from repetition, \r\n                        injected humour, or non-characteristic words etc." },
                    new Description() { DescriptionId = 6, CategoryId = 2, DescriptionName = "There are many variations of passages of Lorem Ipsum available, \r\n                        but the majority have suffered alteration in some form, by injected humour, \r\n                        or randomised words which don't look even slightly believable. \r\n                        If you are going to use a passage of Lorem Ipsum, you need to be sure \r\n                        there isn't anything embarrassing hidden in the middle of text. \r\n                        All the Lorem Ipsum generators on the Internet tend to repeat \r\n                        predefined chunks as necessary, making this the first true generator \r\n                        on the Internet. It uses a dictionary of over 200 Latin words, combined \r\n                        with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. \r\n                        The generated Lorem Ipsum is therefore always free from repetition, \r\n                        injected humour, or non-characteristic words etc." },
                    new Description() { DescriptionId = 7, CategoryId = 3, DescriptionName = "There are many variations of passages of Lorem Ipsum available, \r\n                        but the majority have suffered alteration in some form, by injected humour, \r\n                        or randomised words which don't look even slightly believable. \r\n                        If you are going to use a passage of Lorem Ipsum, you need to be sure \r\n                        there isn't anything embarrassing hidden in the middle of text. \r\n                        All the Lorem Ipsum generators on the Internet tend to repeat \r\n                        predefined chunks as necessary, making this the first true generator \r\n                        on the Internet. It uses a dictionary of over 200 Latin words, combined \r\n                        with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. \r\n                        The generated Lorem Ipsum is therefore always free from repetition, \r\n                        injected humour, or non-characteristic words etc." },
                    new Description() { DescriptionId = 8, CategoryId = 3, DescriptionName = "There are many variations of passages of Lorem Ipsum available, \r\n                        but the majority have suffered alteration in some form, by injected humour, \r\n                        or randomised words which don't look even slightly believable. \r\n                        If you are going to use a passage of Lorem Ipsum, you need to be sure \r\n                        there isn't anything embarrassing hidden in the middle of text. \r\n                        All the Lorem Ipsum generators on the Internet tend to repeat \r\n                        predefined chunks as necessary, making this the first true generator \r\n                        on the Internet. It uses a dictionary of over 200 Latin words, combined \r\n                        with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. \r\n                        The generated Lorem Ipsum is therefore always free from repetition, \r\n                        injected humour, or non-characteristic words etc." },
                    new Description() { DescriptionId = 9, CategoryId = 3, DescriptionName = "There are many variations of passages of Lorem Ipsum available, \r\n                        but the majority have suffered alteration in some form, by injected humour, \r\n                        or randomised words which don't look even slightly believable. \r\n                        If you are going to use a passage of Lorem Ipsum, you need to be sure \r\n                        there isn't anything embarrassing hidden in the middle of text. \r\n                        All the Lorem Ipsum generators on the Internet tend to repeat \r\n                        predefined chunks as necessary, making this the first true generator \r\n                        on the Internet. It uses a dictionary of over 200 Latin words, combined \r\n                        with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. \r\n                        The generated Lorem Ipsum is therefore always free from repetition, \r\n                        injected humour, or non-characteristic words etc." },
                    new Description() { DescriptionId = 10, CategoryId = 4, DescriptionName = "There are many variations of passages of Lorem Ipsum available, \r\n                        but the majority have suffered alteration in some form, by injected humour, \r\n                        or randomised words which don't look even slightly believable. \r\n                        If you are going to use a passage of Lorem Ipsum, you need to be sure \r\n                        there isn't anything embarrassing hidden in the middle of text. \r\n                        All the Lorem Ipsum generators on the Internet tend to repeat \r\n                        predefined chunks as necessary, making this the first true generator \r\n                        on the Internet. It uses a dictionary of over 200 Latin words, combined \r\n                        with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. \r\n                        The generated Lorem Ipsum is therefore always free from repetition, \r\n                        injected humour, or non-characteristic words etc." },
                    new Description() { DescriptionId = 11, CategoryId = 4, DescriptionName = "There are many variations of passages of Lorem Ipsum available, \r\n                        but the majority have suffered alteration in some form, by injected humour, \r\n                        or randomised words which don't look even slightly believable. \r\n                        If you are going to use a passage of Lorem Ipsum, you need to be sure \r\n                        there isn't anything embarrassing hidden in the middle of text. \r\n                        All the Lorem Ipsum generators on the Internet tend to repeat \r\n                        predefined chunks as necessary, making this the first true generator \r\n                        on the Internet. It uses a dictionary of over 200 Latin words, combined \r\n                        with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. \r\n                        The generated Lorem Ipsum is therefore always free from repetition, \r\n                        injected humour, or non-characteristic words etc." },
                    new Description() { DescriptionId = 12, CategoryId = 4, DescriptionName = "There are many variations of passages of Lorem Ipsum available, \r\n                        but the majority have suffered alteration in some form, by injected humour, \r\n                        or randomised words which don't look even slightly believable. \r\n                        If you are going to use a passage of Lorem Ipsum, you need to be sure \r\n                        there isn't anything embarrassing hidden in the middle of text. \r\n                        All the Lorem Ipsum generators on the Internet tend to repeat \r\n                        predefined chunks as necessary, making this the first true generator \r\n                        on the Internet. It uses a dictionary of over 200 Latin words, combined \r\n                        with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. \r\n                        The generated Lorem Ipsum is therefore always free from repetition, \r\n                        injected humour, or non-characteristic words etc." },
                    new Description() { DescriptionId = 13, CategoryId = 5, DescriptionName = "There are many variations of passages of Lorem Ipsum available, \r\n                        but the majority have suffered alteration in some form, by injected humour, \r\n                        or randomised words which don't look even slightly believable. \r\n                        If you are going to use a passage of Lorem Ipsum, you need to be sure \r\n                        there isn't anything embarrassing hidden in the middle of text. \r\n                        All the Lorem Ipsum generators on the Internet tend to repeat \r\n                        predefined chunks as necessary, making this the first true generator \r\n                        on the Internet. It uses a dictionary of over 200 Latin words, combined \r\n                        with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. \r\n                        The generated Lorem Ipsum is therefore always free from repetition, \r\n                        injected humour, or non-characteristic words etc." },
                    new Description() { DescriptionId = 14, CategoryId = 5, DescriptionName = "There are many variations of passages of Lorem Ipsum available, \r\n                        but the majority have suffered alteration in some form, by injected humour, \r\n                        or randomised words which don't look even slightly believable. \r\n                        If you are going to use a passage of Lorem Ipsum, you need to be sure \r\n                        there isn't anything embarrassing hidden in the middle of text. \r\n                        All the Lorem Ipsum generators on the Internet tend to repeat \r\n                        predefined chunks as necessary, making this the first true generator \r\n                        on the Internet. It uses a dictionary of over 200 Latin words, combined \r\n                        with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. \r\n                        The generated Lorem Ipsum is therefore always free from repetition, \r\n                        injected humour, or non-characteristic words etc." },
                    new Description() { DescriptionId = 15, CategoryId = 5, DescriptionName = "There are many variations of passages of Lorem Ipsum available, \r\n                        but the majority have suffered alteration in some form, by injected humour, \r\n                        or randomised words which don't look even slightly believable. \r\n                        If you are going to use a passage of Lorem Ipsum, you need to be sure \r\n                        there isn't anything embarrassing hidden in the middle of text. \r\n                        All the Lorem Ipsum generators on the Internet tend to repeat \r\n                        predefined chunks as necessary, making this the first true generator \r\n                        on the Internet. It uses a dictionary of over 200 Latin words, combined \r\n                        with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. \r\n                        The generated Lorem Ipsum is therefore always free from repetition, \r\n                        injected humour, or non-characteristic words etc." }

                );

            modelBuilder.Entity<Image>()
                .HasData(
                    new Image() { ImageId = 1, CategoryId = 1, ImageName = "fitness1.jpg"},
                    new Image() { ImageId = 2, CategoryId = 1, ImageName = "fitness2.jpg" },
                    new Image() { ImageId = 3, CategoryId = 1, ImageName = "fitness3.jpg" },
                    new Image() { ImageId = 4, CategoryId = 2, ImageName = "kickbox1.jpg" },
                    new Image() { ImageId = 5, CategoryId = 2, ImageName = "kickbox2.jpg" },
                    new Image() { ImageId = 6, CategoryId = 2, ImageName = "kickbox3.jpg" },
                    new Image() { ImageId = 7, CategoryId = 3, ImageName = "zumba1.jpg" },
                    new Image() { ImageId = 8, CategoryId = 3, ImageName = "zumba2.jpg" },
                    new Image() { ImageId = 9, CategoryId = 3, ImageName = "zumba3.jpg" },
                    new Image() { ImageId = 10, CategoryId = 4, ImageName = "pilates1.jpg" },
                    new Image() { ImageId = 11, CategoryId = 4, ImageName = "pilates2.jpg" },
                    new Image() { ImageId = 12, CategoryId = 4, ImageName = "pilates3.jpg" },
                    new Image() { ImageId = 13, CategoryId = 5, ImageName = "coaching1.jpg" },
                    new Image() { ImageId = 14, CategoryId = 5, ImageName = "coaching2.jpg" },
                    new Image() { ImageId = 15, CategoryId = 5, ImageName = "coaching3.jpg" }
                );
            modelBuilder.Entity<Trainer>()
                .HasData(
                    new Trainer() { TrainerId=1, CategoryId=1, NameSurname="Yusuf Dilekci", TrainerDescription= "Some quick example text to build on the card title and make up the bulk of the card's content.", TrainerImage="trainer1.jpg"},
                    new Trainer() { TrainerId = 2, CategoryId = 1, NameSurname = "Savas Cebeci", TrainerDescription = "Some quick example text to build on the card title and make up the bulk of the card's content.", TrainerImage = "trainer2.jpg" },
                    new Trainer() { TrainerId = 3, CategoryId = 2, NameSurname = "Birol E.", TrainerDescription = "Some quick example text to build on the card title and make up the bulk of the card's content.", TrainerImage = "trainer3.jpg" },
                    new Trainer() { TrainerId = 4, CategoryId = 3, NameSurname = "Mert A.", TrainerDescription = "Some quick example text to build on the card title and make up the bulk of the card's content.", TrainerImage = "trainer4.jpg" },
                    new Trainer() { TrainerId = 5, CategoryId = 3, NameSurname = "Azat T.", TrainerDescription = "Some quick example text to build on the card title and make up the bulk of the card's content.", TrainerImage = "trainer5.jpg" },
                    new Trainer() { TrainerId = 6, CategoryId = 4, NameSurname = "Oguz R.", TrainerDescription = "Some quick example text to build on the card title and make up the bulk of the card's content.", TrainerImage = "trainer6.jpg" },
                    new Trainer() { TrainerId = 7, CategoryId = 5, NameSurname = "Sadik S.", TrainerDescription = "Some quick example text to build on the card title and make up the bulk of the card's content.", TrainerImage = "trainer7.jpg" }

                );

            base.OnModelCreating(modelBuilder);
        }

        public DbSet<Category> Categories { get; set; }
        public DbSet<Member> Members { get; set; }
        public DbSet<Contact> Contacts { get; set; }
        public DbSet<Trainer> Trainers { get; set; }
        public DbSet<Description> Descriptions { get; set; }
        public DbSet<Image> Images { get; set; }
        public DbSet<MemberCategory> MemberCategories { get; set; }
        public DbSet<MemberTrainer> MemberTrainers { get; set; }
    }
}
